### PR TITLE
added workflow for closing old issues

### LINKED ISSUE #51: ✨[Feature Request]: Workflow for Closing Old Issues
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like a workflow that automatically identifies and closes old issues based on certain criteria, such as no recent activity or being open for a specific duration.

### Use Case

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Benefits

_No response_

### Add ScreenShots

Close Old Iss

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #51 

@sanika391 please review and merge this PR

Also, please add labels to this PR

### CODE REVIEW

**Comment by sanika391** [comment]
Thank you, @Asymtode712 , for addressing issue #51 with this PR. The workflow for closing old issues is a valuable addition to our project.

Please note that while this PR can be merged automatically, we encourage contributors to add more features or improvements if possible. This helps ensure that each PR provides significant value and reduces redundancy in the repository.

Best regards,
Sanika

**Comment by Asymtode712** [comment]
@sanika391 please review and merge this PR

Also, please add labels to this PR

**Comment by sanika391** [comment]
Have already added the label

**Comment by Asymtode712** [comment]
@sanika391 Sorry, but you have not added labels to this PR and haven't merged it yet.

Please check it once

Thank you!

**Pull request closed without merging**
