### PR TITLE
Update-header size reduced for all screens

### PR DESCRIPTION
**Pull request by Rags-Mishra**
### Screenshot
WhatsApp Image 2024-05-17 at 12 19 35 PM

### CODE REVIEW

**Comment by sanika391** [comment]
This issue has been solved earlier by another contributor is their anything else on which you want to work??
you can take time and think on different aspects of it and work ahead in the project. If you need any help do contact. Would be happy to help you with it.

**Comment by Rags-Mishra** [comment]
Alright! Is there any issue I can work on? I will be happy to contribute. There are many issues which are already being handled by other contributors simultaneously so it is hard to pin point a separate issue.
If there's any feature or issue that you have in mind, do tell.

**Comment by sanika391** [comment]
You can definitely work on making the text multi-lingual. Their is static block present if possible try to remove it.
It's Level3 task so I hope you will do it. 
If u need any help I can definitely provide u with it.

**Comment by Rags-Mishra** [comment]
Sure, I will try my best to resolve the issue. Kindly provide any document
or resource as a guide and assign the issue to me.

**Comment by sanika391** [comment]
What kind of resources you want??

**Comment by Rags-Mishra** [comment]
How do I make text multilingual? Is there any specific package in flutter
for such purpose?

**Comment by sanika391** [comment]
To make your Flutter app multilingual, you can use the intl package, which
provides internationalization and localization support. Here's a
step-by-step guide to setting it up:

1. Add the intl package to your pubspec.yaml file
First, add the intl package and the flutter_localizations package (for
Flutter's localization support) to  pubspec.yaml.
2. Create Localization Files
Create ARB (Application Resource Bundle) files for each language you want
to support. These files are JSON files that contain key-value pairs for
your localized strings.
3. Generate the Localization Classes
Use the intl_translation tool to generate localization classes. You need to
install the intl_translation package.
4. Configure Your App for Localization
Modify your main.dart to include localization support

By following these steps, you can make your Flutter app multilingual using
the intl package and localization files. The intl_translation tool helps
generate the necessary localization classes, making it easier to manage and
use localized strings in your app.
If still their is any confusion then do let me know I will help you with it.

**Comment by sanika391** [comment]
Screenshot 2024-05-22 214819

**Pull request closed without merging**
