### PR TITLE
Dark mode feature added

### PR DESCRIPTION
**Pull request by SumitPareek2401**
Fixes: 
#18 

Feature description:
Dark Mode and Light Mode features added which can make the app more visually appealing while also offering benefits like battery saving and reduced eye strain.

Screen recording:

https://github.com/sanika391/SpoonShare/assets/122019171/f19697e6-96e3-44c6-a30b-5002fa746826

### CODE REVIEW

**Comment by sanika391** [comment]
Screenshot 2024-05-21 194350
I am currently facing a merge conflict issue with the lib/onboarding.dart file in my repository. Here is a screenshot of the conflict markers indicating the problem

**Comment by SumitPareek2401** [comment]
@sanika391 If a conflict arises due to one file lib/onboarding.dart. Can I remove this file from my pull request to merge it? In the future if onboarding.dart file needs to be fixed we can create another pull request.

**Comment by sanika391** [comment]
Sure, no problem.

**Comment by SumitPareek2401** [comment]
@sanika391 Done from my side. Could you try to merge it?

**Comment by sanika391** [comment]
Still the same

**Comment by SumitPareek2401** [comment]
This image is not visible.

**Comment by sanika391** [comment]
Please check now.

**Comment by sanika391** [comment]
Screenshot 2024-05-22 214724

**Comment by SumitPareek2401** [comment]
@Saumya-28 and @sanika391  can you suggest the reason why these files are conflicting?

**Comment by sanika391** [comment]
Hello @SumitPareek2401,

The conflicts in the files lib/onboarding.dart, lib/screens/dashboard/dashboard_home.dart, and lib/screens/home/home_page.dart likely occur because these files have been modified in both the main branch and your feature branch (DarkModeFeatureAdded). When there are changes in the same lines or sections of the code in different branches, Git flags them as conflicts that need manual resolution.

Once you have resolved the conflicts and pushed the changes, please let me know so we can proceed with the review and merging of your pull request.

If you need any further assistance, feel free to ask.

Best regards,
Sanika Chavan
[https://www.linkedin.com/in/sanika-chavan-52457b236]

**Pull request closed without merging**
