### PR TITLE
[FIX] Fixed overlapping of text in login screen and sign up screen.

### PR DESCRIPTION
**Pull request by ascoder1109**
Fixed overlapping of text in login screen, sign up screen and fixed some typos:

spoon_share_login

spoon_share_sign_up

### CODE REVIEW

**Comment by sanika391** [comment]
Another contributor has already fixed this issue. Is their anything on which you want to work??

**Comment by sanika391** [comment]
I am not getting what you are saying?

**Comment by ascoder1109** [comment]
Actually there was an issue from my side. I have closed the merge request.

**Comment by sanika391** [comment]
Ok, thanks.

**Pull request closed without merging**
