### PR TITLE
Fixed video embedding problem in README.md file

### PR DESCRIPTION
**Pull request by Mastermind-sap**
Fixed up the youtube video embed problem in `README.md` file.
Also just a suggestion please don't keep two files with the same name like `Contributing.md` and `CONTRIBUTING.md`. I think it is not recommended and also there are some problems with the directory when I pulled the repo to my local directory.

### CODE REVIEW

**Comment by sanika391** [comment]
Ok. I will definitely look into it.
You have not star the repository and not even clicked on watched. Just do that so that I can merge the pull request.

**Comment by Mastermind-sap** [comment]
why is it necessary to star and watch it? @sanika391 
I will do it anyways but just wanted to ask why is it neccessary.

**Comment by sanika391** [comment]
Because we have been given the guildenes before accepting and pull request
and giving you labels. As these things are necessary.
Once you have completed it will showcase on your leaderboard.

**Comment by Mastermind-sap** [comment]
ok, I have starred and watched it.

**Comment by sanika391** [comment]
Great.
I will look into it and get back to you once I reached home.

**Pull request merged**
