### PR TITLE
AI ChatBot

### PR DESCRIPTION
**Pull request by vishalmaurya850**
# Pull Request

### Checklist 

- [x] I have tested the changes locally
- [ ] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### CODE REVIEW

**Review by vishalmaurya850 — COMMENTED** [review]
I have checked it. You test the App

**Comment by sanika391** [comment]
Great job, @vishalmaurya850! 🌟

Your work on adding the chatbot feature is truly appreciated. This is a fantastic addition to the project, providing much-needed assistance to donors and recipients. Your detailed commits and thorough testing demonstrate excellent dedication and skill. Keep up the amazing work! 🚀

Regards,
Sanika Chavan.
[https://www.linkedin.com/in/sanika-chavan-52457b236]

**Comment by vishalmaurya850** [comment]
Thanks

**Comment by sanjay-kv** [comment]
@sanika391 

There is some major issue happened, you have changed the URL and didn't let us know about this change
image
image
In our system its still the old link you gave us. 

because this all of the contributions done on your repo is not counted. and we are helpless at the contributor. 
this issue affected everyone who contributed to your project. this is very unfortunate situation. 

We updated this multiple time via mail and discord communications and changes let us know via mail.

**Comment by sanika391** [comment]
Thank you for bringing this to my attention. I understand the importance of
accurately tracking contributions, and I’m sorry to hear that you’re
experiencing issues.

Since the URL hasn’t been changed and other contributors are seeing their
contributions, the issue might be specific to your access or view. Here are
a few steps we can take to resolve this:

   1. *Double-Check the URL:* Ensure that you’re using the correct and
   updated URL. Sometimes minor errors in the link can cause issues.
   2. *Clear Cache and Cookies:* Try clearing your browser’s cache and
   cookies, as this can sometimes resolve display issues.
   3. *Check Permissions:* Verify that you have the correct permissions and
   access to view the contributions on the project repository.
   4. *Sync with Project Maintainers:* I’ll also reach out to the project
   maintainers to ensure there’s no issue on their end.

Please let me know if these steps help or if there’s anything else I can
assist with. I’m committed to resolving this issue as quickly as possible
and ensuring that all contributions are properly recognized.

Thank you for your patience and understanding.

Best regards,
Sanika Chavan

**Pull request merged**
