### PR TITLE
overlapping of text in login page can be resized

### PR DESCRIPTION
**Pull request by Nandhinirameshmala**
##fixes issue #1

### CODE REVIEW

**Comment by sanika391** [comment]
Just a friendly remainder do star the repository and click on watched so that I can merge the pull request.

**Comment by sanika391** [comment]
Thank you so much for this. The text is now looking nice. Great Work!!!

**Comment by Nandhinirameshmala** [comment]
i have stared the respository and watched now can u able to pull request

**Comment by sanika391** [comment]
I have merged it. You can check it now.

**Pull request merged**
