### PR TITLE
Created Issue forms and made the issue options more visually appealing

### PR DESCRIPTION
**Pull request by TonyStark-47**
#### Results Screenshots:
- Issue templates:

Screenshot from 2024-05-22 10-41-55

- Bug report (example):

Screenshot from 2024-05-22 10-43-31
Screenshot from 2024-05-22 10-43-55

### CODE REVIEW

**Comment by sanika391** [comment]
Hello Tony,

Thank you for your contribution and for making the issue options more visually appealing!

I see that your pull request #45 addresses issue #44. The results look great, and I appreciate the effort you put into creating the issue forms.

Thank you for your valuable contribution!

Best regards,  
Sanika Chavan

**Comment by TonyStark-47** [comment]
Thank you very much, @sanika391

**Comment by TonyStark-47** [comment]
Hey @sanika391, please put proper 'gssoc' label. Thank you.

**Comment by sanika391** [comment]
Fixed!

**Pull request merged**
