### PR TITLE
PULL-REQUEST-TEMPLATE-#19

### PR DESCRIPTION
**Pull request by anglerfishlyy**
**fixes#19**
---

**Description**:

 - This pull request introduces a pull request template file to improve the process of creating new pull requests within the repository.

 - By implementing a template, we aim to ensure that all pull requests contain essential information, enabling quicker review and more efficient collaboration between contributors/ us and maintainers/you.

 - The template includes sections for providing a clear title, a concise description of the changes, a list of tasks completed, any relevant _issue reference_s, and additional context or considerations.

 - By utilizing this template, we improve consistency, and communication throughout the pull request review process, ultimately improving the overall quality and effectiveness of contributions to the project.

### CODE REVIEW

**Comment by sanika391** [comment]
Please note that according to the rules, I have mentioned the GSOC level in the documentation and refrained from specifying any other levels. This aligns with the guidelines and maintains compliance.

Thank you all for your collaboration and support in making this enhancement possible. Let's continue to strive for excellence in our contributions.

**Comment by sanika391** [comment]
Just a friendly reminder, please make sure to star the repository and click on "Watch" to stay updated with the latest developments and changes in the project.

**Comment by sanika391** [comment]
Hello [anglerfishlyy](https://github.com/anglerfishlyy) hope you are doing well.....
I have sent you this msg long time ago but still not you have not replied to me. So can you give me an update or may I assign this issue to someone else??

**Comment by anglerfishlyy** [comment]
@anglerfishlyy
[PULL-REQUEST-TEMPLATE-](https://github.com/sanika391/SpoonShare/pull/20/commits/e66bc955749f461a24cdcd225ac7fb77ae088f05)https://github.com/sanika391/SpoonShare/issues/19 , should i change it or what should i do ?

**Comment by sanika391** [comment]
Its been 4 days, thought that you are not active. But still 1 day is remaining if you want to solve this issue you can go ahead. But till tomorrow do send me the changes or going by the rule book i will have to assign it to another contributor.

**Comment by anglerfishlyy** [comment]
What specifically do you want me to add in PR template, mam?

**Comment by sanika391** [comment]
It looks like you've successfully merged the pull request related to the pull request template enhancement. Well done on that! If there's anything else you need assistance with or if there are more tasks you'd like to tackle, feel free to let me know.

Great to connect with you. Thank you for your valuable contribution.

**Pull request merged**
