### PR TITLE
added workflow as mentioned in issue #48

### LINKED ISSUE #48: ✨[Feature Request]: Auto Commenting Feat for Issue Creation
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like an automated feature that posts a predefined comment on an issue as soon as it is created. This comment could include acknowledgment of the issue, guidelines for further steps, or any other relevant information. The automation should be customizable to accommodate different project workflows and communication styles.

### Use Case

This feature aims to address the problem of delayed and inconsistent communication following the creation of issues. By automatically commenting on issues as soon as they are created, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

### Benefits

_No response_

### Add ScreenShots

issue creation

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

### PR DESCRIPTION
**Pull request by Asymtode712**
Fixes #48 

@sanika391 please review and merge this PR

Also, please add labels to this PR

### CODE REVIEW

**Comment by sanika391** [comment]
[Asymtode712](https://github.com/Asymtode712)

Thank you so much for providing these detailed steps. They were incredibly helpful and clear. I have successfully navigated through the process of creating a Personal Access Token with the necessary permissions and assigning it to the GITHUB_TOKEN environment variable. Your instructions on navigating the settings and configuring the token and repository secrets were spot-on.

This guidance ensures that the workflows can run smoothly, and I appreciate your proactive support in making sure everything is set up correctly. It's great to connect with you and I look forward to more collaboration as we continue to improve our project.

Best regards,
Sanika Chavana
[https://www.linkedin.com/in/sanika-chavan-52457b236]

**Comment by Asymtode712** [comment]
@sanika391 please add labels to every merged PR.

Also, Thank you for your kind words🙏🏼

**Comment by sanika391** [comment]
Will do!

**Comment by Asymtode712** [comment]
@sanika391 my merged PRs on this repo are not visible on the leaderboard and the reason this is because is that your '(gssoc)' label is written wrongly it must be 'gssoc'

Please correct it
Thank you!

**Pull request merged**
