### PR TITLE
Integrated Dockerfile in the project

### PR DESCRIPTION
**Pull request by Ratangulati**
#93 

### Title
I added Dockerfile and docker-compose for the project and updated the docs accordingly.

### Checklist 

- [x] I have tested the changes locally
- [x] Documentation has been updated (if necessary)
- [x] Changes are backward-compatible

### CODE REVIEW

**Comment by Ratangulati** [comment]
@sanika391 I have added the Dockerfile and docker-compose for the project, please review the code. 
Can you please do it level 2? I have integrated docker and docker-compose with docs.
Thankyou

**Comment by sanika391** [comment]
Great job integrating the Dockerfile and docker-compose into the project, Ratangulati! This will definitely streamline our development and deployment processes. Thanks for updating the documentation as well. Everything looks good to me.

I have added level 2 also....

Regards,
Sanika Chavan.
[https://www.linkedin.com/in/sanika-chavan-52457b236]

**Comment by Ratangulati** [comment]
Thank you for adding level2
Will try to find more issues and solve it.
Regards
Ratan Gulati

**Comment by sanika391** [comment]
Sure, no problem.

**Pull request merged**
